name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04]
      fail-fast: false
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install prerequisites (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y zlib1g-dev unzip cmake gcc g++
      - name: Install prerequisites (Mac)
        if: matrix.os == 'macos-latest'
        run: brew install unzip
      - name: Install SVF Tools
        run: npm install -g svf-lib
      - name: Compile example.c
        run: clang -S -c -g -fno-discard-value-names -emit-llvm example.c -o example.ll
      - name: Run demo
        run: ./gradlew runDemo --args="example.ll" --info
      - name: Archive build
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Java SVF ${{ matrix.os }}
          path: build
      - name: Upload produced graphs
        uses: actions/upload-artifact@v3
        with:
          name: Graphs (${{ matrix.os }})
          path: graphs
